term.clear()
term.setCursorPos(1,1)
term.setTextColor(colors.yellow)
write("CraftOS 1.8 ")
term.setTextColor(colors.purple)
textutils.slowWrite("Running DASL 1.0.1\n")
term.setTextColor(colors.white)
sleep(1)
shell.run("motd")
shell.run("/dasl/dasl")