term.clear()
term.setCursorPos(1,1)
term.setTextColor(colors.yellow)
write("CraftOS 1.8 ")
term.setTextColor(colors.purple)
write("(DASL 1.0.1)\n")
term.setTextColor(colors.white)
shell.run("alias cls clear")
shell.run("motd")
shell.run("/dasl/dasl")